### ISSUE TITLE
[BUG] Maestro is completely blocked

### ISSUE THREAD

**Issue by dragonfire1119** [gunnartorfis/sonner-native#137]
**Describe the bug**

The Maestro test can't see anything to click on.

**To Reproduce**

When I add in:

```
<TabNavigation />
            <Toaster />
```

If I remove `<Toaster />` my tests pass with the overlay gone.

**Expected behavior**
For Maestro to be able to click on buttons.

**Environment info**

| Library                      | Version |
| ---------------------------- | ------- |
| sonner-native                | 0.15.0   |
| react-native                 | 0.75.4   |
| react-native-reanimated      | 3.15.4   |
| react-native-gesture-handler | 2.20.0   |

**Comment by gunnartorfis** [comment]
If you use the element inspector, you're able to click through it while the toast is visible, right? 
Since that's the case for me at least, I don't think there's much to be done here. I'd suggest conditionally render the Toaster if the Maestro test is running. While I didn't find a React Native implementation of detecting that Maestro is running, you could always create a native module that surfaces that: https://maestro.mobile.dev/advanced/detect-maestro-in-your-app
